# Generated by Django 5.2.5 on 2025-09-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_exam_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
