# Generated by Django 5.2.5 on 2025-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_examattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='admin', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
