# Generated by Django 5.2.5 on 2025-09-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_user_role_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MHQ', 'MHQ'), ('true/false', 'true/flase'), ('essay', 'Essay')], default='MHQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='student', max_length=20, null=True),
        ),
    ]
