# Generated by Django 5.2.5 on 2025-09-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_question_answer_remove_question_exam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='grade',
            new_name='point',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='admin', max_length=20, null=True),
        ),
    ]
